"""Locked measurement primitives."""

from pprs.analysis.metrics import (
    PI_GRID,
    SummEvalPolarity,
    danger_quadrant,
    human_response_set,
    human_response_set_surface,
    shannon_entropy_bits,
    summeval_distribution,
    threshold_surface,
)
from pprs.analysis.response_sets import (
    PinnedAggregation,
    aggregate_pinned_choices,
    beta_pin,
    beta_self,
    h_seed,
)
from pprs.analysis.inference import (
    DangerCell,
    H1Inference,
    H2Inference,
    H3Inference,
    H3Observation,
    PlaceboInference,
    PlaceboPairContrast,
    aggregate_full_grid_choices,
    bias_regret,
    consistency_regret,
    h3_item_advantage,
    h1_inference,
    h2_inference,
    h3_inference,
    jaccard_similarity,
    modal_label,
    placebo_flip_contrast,
    placebo_inference,
    select_model,
)
from pprs.analysis.runner import (
    ConfirmatoryAnalysisResult,
    run_confirmatory_analysis,
)

__all__ = [
    "PI_GRID",
    "SummEvalPolarity",
    "danger_quadrant",
    "human_response_set",
    "human_response_set_surface",
    "shannon_entropy_bits",
    "summeval_distribution",
    "threshold_surface",
    "PinnedAggregation",
    "aggregate_pinned_choices",
    "beta_pin",
    "beta_self",
    "h_seed",
    "aggregate_full_grid_choices",
    "bias_regret",
    "consistency_regret",
    "h3_item_advantage",
    "jaccard_similarity",
    "modal_label",
    "placebo_flip_contrast",
    "select_model",
    "DangerCell",
    "H1Inference",
    "H2Inference",
    "H3Inference",
    "H3Observation",
    "h1_inference",
    "h2_inference",
    "h3_inference",
    "PlaceboInference",
    "PlaceboPairContrast",
    "placebo_inference",
    "ConfirmatoryAnalysisResult",
    "run_confirmatory_analysis",
]
